name: github-actions-release
description: Prints out hello
author: echo
branding:
  icon: 'truck'
  color: 'blue'
inputs:
  message_to_print:
    description: 'Hello'
    required: true
runs:
  using: "centos"
  steps:
    - run: "action.sh"
      shell: sh
